Repository tektronix/tsp-toolkit, pull requests merged in 2024-10, with the labels that each got.

#54 Task/tsp 836 enable lua 5.0
  src/extension.ts
  src/tspConfigJsonParser.ts
  src/workspaceManager.ts
Labels: bug, enhancement

#55 Task/tsp 836 enable lua 5.0
  CHANGELOG.md
  package-lock.json
  package.json
  src/workspaceManager.ts
Labels: enhancement

#61 TSP-839 Fix issue with visa connection model and serial number
  CHANGELOG.md
  src/extension.ts
  src/resourceManager.ts
Labels: bug

#64 TSP-839 Fix issue with naming of instrument connection
  CHANGELOG.md
  src/communicationmanager.ts
  src/extension.ts
  src/instruments.ts
Labels: bug

#67 TSP-412 Minor improvements
  src/communicationmanager.ts
  src/instruments.ts
Labels: enhancement

#65 Release v1.0.0
  CHANGELOG.md
  README.md
  package-lock.json
  package.json
  resources/DemoVideoThumbnail.jpg
  resources/DemoVideoThumbnail.png
  resources/DemoVideoThumbnail_play.jpg
  src/extension.ts
  src/instruments.ts
Labels: enhancement
