Repository tektronix/tsp-toolkit, pull requests merged in 2024-08, with the labels that each got.

#39 Task/tsp 773 fix tspop connection
  CHANGELOG.md
  package-lock.json
  package.json
  src/communicationmanager.ts
  src/extension.ts
  src/instruments.ts
  src/resourceManager.ts
Labels: bug

#42 Task/tsp 792 add a plus button to the instruments pane title bar
  package.json
  resources/dark/connect.svg
  resources/light/connect.svg
  src/extension.ts
Labels: enhancement

#43 updating version and changelog to cut internal release
  CHANGELOG.md
  package-lock.json
  package.json
Labels: bug, enhancement
